### PR TITLE
"Enhancement" issue PR

### PR DESCRIPTION
**Pull request by zanni**
Hi,
This pull request implements the few points we discussed in "Enhancement" issue:
- OADR payload marshalling/unmarshalling using "jsonix" npm module. Only 2.0b profile is implemented for now but 2.0a would be easy to add.
- xmlSignature using "xmldsigjs" npm module. It supports only RSA keys for now
- an example of the externalization of API I propose in "RegisterReport" method of oadr2/oadr2-ven.js
- node-red flows I use, in example-flows/avobflow.json

Moreover, I had to change the "sendRequest" API in order to use promise, as "xmldsigjs" use those in it's API. It is not a bad thing because it should make response callback easier to write.

You should test those modifications against your use cases to ensure I did not break some things.

Bertrand

### CODE REVIEW

**Comment by bnystrom** [comment]
Hi Bertrand,

I've been trying to test your pull request without much success. Perhaps I
am doing something wrong. My test case is against the Nebland OpenADR VTN
test tool, and I am not sending signed XML/ SSL/TLS. The flows produce an
XML message that seems to more represent a 2.0a formatted package. It is
void of an <oadrPayload> and <oadrSignedObject> wrapper. Even without doing
signed objects it is my understanding that 2.0b should still retain those
outer parents. Here is a simple example of what I expect:

<?xml
<oadrPayload.....
    <oadrSignedObject.....
        <oadrQueryRegistration.....
            .......
        </oadrQueryRegistration>
    </oadrSignedObjec>
</oadrPayload>

But this is what I am getting

<oadrQueryRegistraion.....
</oadrQueryRegistration>

No Payload or SignedObject wrappers. Of course, this means that my tests
fail to communicate with the Nebland VTN test tool.
Unfortunately, I've also not been able to compile the jasonix tool used to
generate the models. I haven't spent a lot of time trying to get that to
work, but if I'm not able to do that it would not make sense for me to
support jasonix if I can not reliably reproduce the models in the future
(but that is currently a secondary concern to getting the proper XML
structure).

Have you tried testing on your end without assigning signed XML, etc.? As I
mentioned, perhaps it is a setting or something on my end that is keeping
the outer XML parents from being produced.


Best Regards
Bryan Nystrom

**Comment by zanni** [comment]
Hi Bryan

According to my understanding of openADR20b, you should not send OadrPayload message when you are not using xmlSignature profile setting.

For example:
< oadrQueryRegistration.....
</oadrQueryRegistration>

became:
<?xml
<oadrPayload.....
<oadrSignedObject.....
<oadrQueryRegistration.....
.......
</oadrQueryRegistration>
</oadrSignedObjec>
<Signature>…</>Signature
</oadrPayload>

when you set xmlSignature.

This behavior seems to be validated by OpenAdr specifications:
https://cimug.ucaiug.org/Projects/CIM-OpenADR/Shared%20Documents/Source%20Documents/OpenADR%20Alliance/OpenADR_2_0b_Profile_Specification_v1.0.pdf <https://cimug.ucaiug.org/Projects/CIM-OpenADR/Shared%20Documents/Source%20Documents/OpenADR%20Alliance/OpenADR_2_0b_Profile_Specification_v1.0.pdf>
8.4 OpenADR 2.0b Registration Service
10.6.3 Creating  XML Signatures

In those examples, Registration Service use oadrQueryRegistration payload. OadrPayload are used when the message is signed.

Regarding jsonix, you can generate the schema by executing a jar against OpenADR XSD files. I can push a script to generate the schema if needed

Best regards
Bertrand Zanni

**Comment by zanni** [comment]
Hi Bryan,

I take a second look at OpenADR specification and I didn’t find a reference to using OadrPayload without using xmlSignature but I can be wrong

Actually it is pretty simple to use the OadrPayload wrapper even if xmlSignature is not set:
In the file oadr2/oadr2b-payload.js

change the function:
var transform = function(payloadType, payload) {
	if(!xmlSignature){
		return new Promise((resolve) => {resolve( marshal(payloadType, payload))});
	}else {
		return sign(payloadType, payload);
	}
}

to:
var transform = function(payloadType, payload) {
	if(!xmlSignature){
		var env = {}; 
		env[payloadType] = payload 
		env.id = "signedObject » 
		var envelop = { oadrSignedObject: env, }
		return new Promise((resolve) => {resolve( marshal("oadrPayload", envelop))});
	}else {
		return sign(payloadType, payload);
	}
}

I hope it helps !

Bertrand Zanni

**Comment by bnystrom** [comment]
Thanks, Bertrand!

I'll do a bit more digging on this on my end to see why the Nebland VTN
isn't accepting the format being used by the jasonix version.
In regards to the model builder, I've only tried to get it to work on an
Ubuntu workstation (18.04). I didn't spend much time on it since you
already have models built.

Also, I'm not sure if your intention was to include your demo flows in
the npm package, but given that it requires BACNet nodes it probably isn't
something we'll add. Still, it is nice (for me anyway) to have it as a
reference here though.

Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
B.

Logically it makes little sense to wrap the object in a
Payload+SignedObject if the only real purpose of those layers is to provide
a signature.

Thanks for the work-around example. We'll use that only if we need to. I
want to do it the correct way in the end. The Nebland tool should be
reliable since they say they work in conjunction with QualityLogic testing
tools (kind'a the standard for testing). I'm going to also set up the
Nebland VEN tools and monitor the packets between their VEN and VTN to see
if they send Payload/SignedObject when not using signed XML.

Once again, thanks for your help.

Best Regards
Bryan Nystrom

**Comment by zanni** [comment]
I intended to include my demo flow because I might have changed some functions, especially in the «  Response » part, but yes, I forgot the BACNet module. By the way, this is how I use your library, as a mean to abstract various IoT protocol: node-red + openadr is a great way to speed up IoT prototyping and integration.

Best regards,
Bertrand Zanni

**Comment by bnystrom** [comment]
Best Regards
Bryan Nystrom

That's awesome.

I work on a lot of IoT things here along with various standards like OCPP,
BACNet, Modbus, OpenADR, SEP2.0/2030.5..... It's been a few months since I
actually worked on the OpenADR stuff, so for some reason I *totally forgot*
that OpenADR REQUIRES SSL/TLS. I'm not sure why I thought I could use it
without. Having said that, I think that once I add a certificate, your pull
request will work just fine. I apologize for the confusion (on my part).
I'll add a TLS cert and retest.

Out of curiosity, which BACNet Node-Red nodes are you using?

**Comment by zanni** [comment]
Hi Bryan,

Currently we are testing the following bacnet module:
https://flows.nodered.org/node/node-red-contrib-bacnet <https://flows.nodered.org/node/node-red-contrib-bacnet>
However it is not ready for production

I think I might have another pull request containing few stuff, like xmldsig message validation (it currently just sign) and some request (oadrCanceledPartyRegistration). Do you want me push to those future changes ?

Best regards,

Bertrand

**Comment by bnystrom** [comment]
Bertrand,

Yes, go ahead and push the newer changes. I'll use  new pull request
instead of the original one.

After you make the next pull request however, I'll be making a few changes
to support non-signed messages. (You'll probably want to test with my
changes before we make the final release to see if I break anything on your
end regarding signed objects)

Due to the fact that I can not get the Nebland test tools to work without
having a payload/signedObject wrapper, even without it being an
xmlSignedObject, and the fact that I have found a couple of official
documents on OpenADR where the examples also show 2.0b messages being sent
with those wrappers when not actually being signed, I am going to be making
your suggested changes to "transform" function to support having those
wrappers.

When I do that, there are a couple of other places that need to be changed
to support it. In particular, in the prepareResMsg (and probably also the
prepareReqMsg) functions in the oadr2-ven.js file, you use an index into
the returned data in order to pull out the msg.payload.data section. This
index appears to need to be different if the message actually has an
xmlSignedObject or not. I also am not keen on using an index that may
change so I am thinking of finding the msg.payload.data section based off
the fact that the key starts with an "oadr" prefix. Otherwise I'll adjust
the index based on if we see a "Signature" key in the data we are parsing.

One other thing I am going to change unless you have a strong preference to
keep it is the removal of the "TYPE_NAME" key/value pair that is added by
jsonix. I don't want to polute the msg.payload.data value that Node-Red
users will have to deal with. BUT, if you have a reason for leaving that
"TYPE_NAME" data in the msg.payload.data, let me know.


Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
Bertrand,

Sorry, just one more thing. Please post your next pull request against the
*develop* branch instead of the *master* branch. Right now they are at the
same head, so there shouldn't be a problem for you to do this. (I try to
use the *GitFlow* method, so nothing goes into master/release until the
final build of develop is approved)

Best Regards
Bryan Nystrom

**Comment by zanni** [comment]
Bryan,

Ok I will probably make my pull request tomorrow or the day after and I will ensure to push it into the develop branch.

Is it possible to « flag» the usage of oadrPayload (signedObject wrapper) for non-signed payload in the oadrProfile ?
For example, we can add a useOadrPayload=true to the profile when user make createPartyRegistration payload to activate the feature. useOadrPayload should automatically be set to true (or ignored) when xmlSignature=true.

It is ok for me to remove «  TYPE_NAME » from jsonix returned message. It is probably there for reflection purpose but I don’t use the feature so it’s up to you.

Best regards,
Bertrand Zanni

**Comment by bnystrom** [comment]
I'm open to making the outer envelopes (payload/signedObject) either a flag
or a setting in the node configuration. I'm still debating on if it should
default to true or false however. Given the examples and the Nebland tools,
I am leaning towards making that a default of true. I am still searching
for a definitive answer as to if the outer envelopes are required or not
when not using signed xml objects. The specs and the schema seem vague.

Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
Bertrand,

Just wanted to pass along a link to an oadr document that has several
example payloads where they are not using xml signatures but still have an
<oadrPayload><oadrSignedObject> envelope.

https://www.openadr.org/assets/openadr_drprogramguide1.0.pdf

I've seen it elsewhere also, but his document has several examples.

Best Regards
Bryan Nystrom

**Comment by zanni** [comment]
Bryan,

Yes indeed it seems that the signature wrapper is widely used even when no signature is present. I still think the feature (no wrapper when no xmlSignature) should be kept with a flag (useOadrPayload), but this flag should probably be default to true.

Thanks for the document, it contains several use case I didn’t know and I want to explore !

Best Regards,
Bertrand Zanni

**Pull request merged**
